server:
  port: 8082

spring:
  application:
    name: ADMIN-SERVICE
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:/data/sampledata;AUTO_SERVER=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect

eureka:
  instance:
    client:
      serverUrl:
        defaultZone: http://localhost:8761/eureka/